[package]
name = "compositor_y5_select_overlay_interface"
version = "0.0.1"
edition = "2024"

[dependencies]
smithay = { workspace = true }
uuid = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_seat_gesture_touch = { workspace = true }
compositor_orchestration_driver_selection_base = { workspace = true }
compositor_orchestration_draw_layer_base = { workspace = true }
compositor_support_world_order_track_base = { workspace = true }
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_monitor_selection_scene_base = { workspace = true }
compositor_monitor_selection_font_base = { workspace = true }
compositor_y5_surface_draw_handle = { workspace = true }
compositor_y5_surface_protocol_base = { workspace = true }
compositor_remote_message_client_base = { workspace = true }
compositor_remote_client_handle_selection = { workspace = true }
compositor_remote_client_handle_aspect = { workspace = true }
compositor_developer_debug_instance_record = { workspace = true }

[lib]
path = "lib.rs"
