[package]
name = "compositor_remote_client_handle_base"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_orchestration_core_state_base = { workspace = true }
compositor_remote_client_handle_aspect = { workspace = true }
compositor_remote_client_handle_debug = { workspace = true }
compositor_remote_client_handle_shader = { workspace = true }
compositor_remote_client_handle_navigator = { workspace = true }
compositor_remote_client_handle_selection = { workspace = true }
compositor_remote_message_client_base = { workspace = true }
