[package]
name = "compositor_y5_picker_seat_touch"
version = "0.0.1"
edition = "2024"

[dependencies]
smithay = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_seat_pointer_input = { workspace = true }
compositor_y5_picker_seat_pointer = { workspace = true }

[lib]
path = "lib.rs"
