//! `y5.compositor.uninstall` — the generated command that removes what the installer
//! placed.

use compositor_installer_process_config_parse_base::Preset;

/// The `/usr/bin/y5.compositor.uninstall` script.
///
/// Generated per-install so the preset-derived names (binary, wrapper, service, session
/// entry, portal config) are the real ones. The OPTIONAL components — devtool, polkit,
/// MX daemon, Xwayland, PAM — are listed unconditionally and removed only if present:
/// the script cannot know which were chosen, and remove-if-present is both simpler and
/// more correct than a recorded manifest that could drift from the disk.
///
/// User configuration is KEPT unless `--purge`. An uninstall is usually a step in
/// reinstalling, and destroying a tuned `settings.json` (or the persisted world state
/// beside it) is not recoverable.
pub fn uninstall_script(p: &Preset) -> String {
    format!(
        "#!/bin/bash\n\
         # /usr/bin/y5.compositor.uninstall — generated by the y5 installer.\n\
         # Removes what the installer placed. User config is kept unless --purge.\n\
         set -u\n\
         \n\
         PURGE=0\n\
         case \"${{1:-}}\" in\n\
         \x20   --purge) PURGE=1 ;;\n\
         \x20   -h|--help)\n\
         \x20       echo \"usage: y5.compositor.uninstall [--purge]\"\n\
         \x20       echo \"  --purge  also delete ~/.config/y5.compositor\"\n\
         \x20       exit 0 ;;\n\
         \x20   \"\") ;;\n\
         \x20   *) echo \"unknown argument: $1\" >&2; exit 2 ;;\n\
         esac\n\
         \n\
         SUDO=\"\"\n\
         [ \"$(id -u)\" -ne 0 ] && SUDO=sudo\n\
         CFG=\"${{XDG_CONFIG_HOME:-$HOME/.config}}\"\n\
         UD=\"$CFG/systemd/user\"\n\
         \n\
         echo \":: stopping and disabling user units\"\n\
         for unit in {service} xwayland.service mx-gesture-daemon.service \\\n\
         \x20           y5-polkit-agent.service; do\n\
         \x20   systemctl --user disable --now \"$unit\" >/dev/null 2>&1 || true\n\
         done\n\
         rm -f \"$UD/{service}\" \"$UD/{shutdown}\" \"$UD/xwayland.service\" \\\n\
         \x20      \"$UD/mx-gesture-daemon.service\" \"$UD/y5-polkit-agent.service\"\n\
         systemctl --user daemon-reload >/dev/null 2>&1 || true\n\
         \n\
         echo \":: removing user-owned files\"\n\
         rm -f \"$HOME/.local/bin/mx-gesture-daemon\"\n\
         rm -f \"$CFG/mx-gesture-daemon/config.toml\"\n\
         rm -f \"$CFG/xdg-desktop-portal/{desktop}-portals.conf\"\n\
         \n\
         echo \":: removing system files (sudo)\"\n\
         $SUDO rm -f /usr/bin/{binary} /usr/bin/{wrapper} \\\n\
         \x20   /usr/bin/y5.compositor.settings /usr/bin/y5.compositor.monitor \\\n\
         \x20   /usr/bin/xwayland-satellite /usr/local/bin/y5-polkit-agent \\\n\
         \x20   /usr/share/wayland-sessions/{session} \\\n\
         \x20   /usr/share/applications/y5.compositor.monitor.desktop \\\n\
         \x20   /etc/pam.d/y5-lock /etc/udev/rules.d/42-logitech-hidpp.rules \\\n\
         \x20   /usr/bin/y5.compositor.update\n\
         $SUDO udevadm control --reload >/dev/null 2>&1 || true\n\
         \n\
         if [ \"$PURGE\" -eq 1 ]; then\n\
         \x20   echo \":: purging $CFG/y5.compositor\"\n\
         \x20   rm -rf \"$CFG/y5.compositor\"\n\
         else\n\
         \x20   echo \":: keeping $CFG/y5.compositor (pass --purge to delete it)\"\n\
         fi\n\
         \n\
         echo \"Uninstalled. Log out to drop the session from your display manager.\"\n\
         $SUDO rm -f /usr/bin/y5.compositor.uninstall\n",
        binary = p.binary,
        wrapper = p.wrapper,
        service = p.service,
        shutdown = shutdown_target_name(&p.service),
        session = p.wayland_session,
        desktop = p.desktop_name,
    )
}

/// `y5.service` -> `y5.shutdown.target`. Mirrors `compute.plan`'s private helper so the
/// uninstaller names the same file the installer placed.
fn shutdown_target_name(service: &str) -> String {
    format!("{}.shutdown.target", service.strip_suffix(".service").unwrap_or(service))
}
