[package]
name = "compositor_y5_surface_protocol_base"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_y5_group_protocol_base.workspace = true
compositor_y5_group_surface_base.workspace = true
compositor_y5_lock_interface_surface.workspace = true
compositor_y5_picker_surface_view.workspace = true
compositor_y5_guide_menu_view = { workspace = true }
compositor_y5_touch_pane_view.workspace = true
compositor_y5_osk_board_view.workspace = true
compositor_y5_overview_state_base.workspace = true
compositor_configurator_settings_surface_message.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_y5_placeholder_protocol_base.workspace = true
compositor_y5_launcher_protocol_message.workspace = true
compositor_y5_graphic_capture_session.workspace = true
compositor_monitor_selection_scene_base.workspace = true

[lib]
path = "lib.rs"
