[package]
name = "compositor_background_two_worker_ensure"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_background_two_worker_alloc = { workspace = true }
compositor_background_two_worker_device = { workspace = true }
compositor_background_two_worker_pane = { workspace = true }
compositor_background_two_worker_target = { workspace = true }

[lib]
path = "lib.rs"
