[package]
name = "compositor_support_bevy_core_worker_slot"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_kernel_graphic_bridge_negotiate_compositor = { workspace = true }
compositor_support_bevy_core_alloc_base = { workspace = true }
compositor_support_bevy_core_context_base = { workspace = true }
compositor_support_bevy_core_fault_base = { workspace = true }
compositor_support_bevy_core_import_base = { workspace = true }
smithay = { workspace = true }
wgpu = { workspace = true }
