[package]
name = "compositor_y5_canvas_draw_scene"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_pipeline_world_system_base = { workspace = true }
compositor_y5_surface_system_base = { workspace = true }
compositor_monitor_compositor_iced_base = { workspace = true }
uuid = { workspace = true }
compositor_y5_window_interface_record = { workspace = true }
compositor_y5_canvas_draw_viewport = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_support_smithay_state_compositor_dispatch.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_orchestration_core_state_base.workspace = true
compositor_y5_canvas_draw_context.workspace = true
compositor_y5_canvas_draw_element.workspace = true
compositor_y5_canvas_cursor_element.workspace = true
compositor_y5_window_draw_frame.workspace = true
compositor_y5_select_box_base.workspace = true
compositor_y5_window_draw_occlude.workspace = true
compositor_y5_camera_transform_translate.workspace = true
compositor_pipeline_abi_descriptor_base.workspace = true
compositor_pipeline_abi_clock_base.workspace = true
compositor_y5_window_draw_moment.workspace = true
compositor_y5_canvas_input_state.workspace = true
[lib]
path = "lib.rs"