[package]
name = "compositor_orchestration_seat_keyboard_input"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_surface_system_base = { workspace = true }
compositor_support_system_input_event_base = { workspace = true }
compositor_orchestration_input_drive_base = { workspace = true }
compositor_y5_overlay_interface_keyboard.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_orchestration_core_state_base.workspace = true
compositor_y5_canvas_input_keyboard.workspace = true
compositor_support_iced_core_engine_base.workspace = true
compositor_monitor_compositor_iced_base.workspace = true
compositor_y5_launcher_input_base.workspace = true
compositor_orchestration_driver_lid_base.workspace = true
compositor_orchestration_driver_settings_base.workspace = true
compositor_developer_environment_preference_base.workspace = true
compositor_orchestration_driver_output_base.workspace = true
[lib]
path = "lib.rs"
