[package]
name = "compositor_y5_window_draw_element"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_orchestration_driver_capture_base = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }


[lib]
path = "lib.rs"
