[package]
name = "compositor_background_two_worker_shared"
version = "0.0.1"
edition = "2024"

[dependencies]
smithay = { workspace = true }
compositor_background_two_worker_base = { workspace = true }
compositor_background_two_worker_target = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }

[lib]
path = "lib.rs"
