[package]
name = "compositor_y5_lock_scene_frame"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_pipeline_world_system_base = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_y5_surface_system_base = { workspace = true }
compositor_background_three_system_base = { workspace = true }
compositor_orchestration_draw_scene_element.workspace = true
compositor_model_debug_instance_record = { workspace = true }
compositor_y5_lock_scene_hook.workspace = true
compositor_y5_lock_interface_base.workspace = true
compositor_support_bevy_core_compositor_base.workspace = true
compositor_background_three_draw_scene.workspace = true
compositor_background_two_draw_scene.workspace = true
compositor_y5_surface_draw_scene.workspace = true
compositor_orchestration_draw_layer_base.workspace = true
compositor_monitor_compositor_iced_base.workspace = true
compositor_background_two_draw_element.workspace = true
compositor_orchestration_draw_dispatch_frame.workspace = true
compositor_orchestration_seat_pointer_draw.workspace = true
compositor_orchestration_core_state_base.workspace = true
compositor_y5_lock_scene_element.workspace = true
bitflags = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
