[package]
name = "compositor_remote_client_handle_aspect"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_y5_select_system_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_remote_message_client_base = { workspace = true }
compositor_support_action_camera_fit_aspect = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_canvas_system_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_window_lifecycle_interface = { workspace = true }
smithay = { workspace = true }
