[package]
name = "compositor_orchestration_seat_pointer_element"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_model_debug_instance_record = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_orchestration_seat_pointer_texture.workspace = true
xcursor.workspace = true
[lib]
path = "lib.rs"