[package]
name = "compositor_y5_osk_board_handle"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_seat_keyboard_input = { workspace = true }
compositor_y5_osk_board_view = { workspace = true }
compositor_y5_osk_board_state = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
