[package]
name = "compositor_support_iced_core_engine_base"
version = "0.1.0"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
iced_core = { workspace = true }
iced_runtime = { workspace = true }
iced_widget = { workspace = true }
iced_graphics = { workspace = true }
iced_wgpu = { workspace = true }
bitflags.workspace = true