[package]
name = "compositor_orchestration_draw_node_base"
version = "0.0.1"
edition = "2024"

[dependencies]
smithay = { workspace = true }
compositor_developer_debug_instance_record = { workspace = true }
compositor_support_system_world_frame_base = { workspace = true }
compositor_orchestration_draw_dispatch_frame = { workspace = true }
compositor_artifact_draw_quad_base = { workspace = true }
compositor_orchestration_draw_scene_element = { workspace = true }
compositor_orchestration_seat_pointer_element = { workspace = true }
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_y5_canvas_draw_element = { workspace = true }
compositor_background_two_draw_element = { workspace = true }
compositor_support_bevy_core_compositor_base = { workspace = true }

[lib]
path = "lib.rs"
