[package]
name = "compositor_y5_picker_world_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_pipeline_world_system_base = { workspace = true }
compositor_support_system_persist_mark_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_support_system_trait_system_base = { workspace = true }
compositor_support_world_kind_build_base = { workspace = true }
compositor_y5_picker_system_base = { workspace = true }
compositor_y5_picker_state_base = { workspace = true }
compositor_y5_picker_interface_base = { workspace = true }
compositor_y5_navigator_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_background_two_system_base = { workspace = true }
compositor_y5_window_system_base = { workspace = true }
compositor_y5_surface_system_base = { workspace = true }
compositor_y5_canvas_system_base = { workspace = true }
compositor_orchestration_seat_system_pointer = { workspace = true }
compositor_y5_placeholder_system_base = { workspace = true }
compositor_y5_launcher_system_base = { workspace = true }
compositor_y5_select_system_base = { workspace = true }
compositor_y5_select_overlay_system = { workspace = true }
compositor_y5_group_system_base = { workspace = true }
compositor_y5_overview_system_base = { workspace = true }
smithay = { workspace = true }

uuid = { workspace = true }

[lib]
path = "lib.rs"
