[package]
name = "compositor_y5_picker_three_scene"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
compositor_support_bevy_core_scene_base = { workspace = true }
compositor_y5_picker_three_state = { workspace = true }
compositor_y5_picker_three_build = { workspace = true }
bevy = { workspace = true }
wgpu = { workspace = true }

[lib]
path = "lib.rs"
