[package]
name = "compositor_kernel_vulkan_memory_upload_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_kernel_vulkan_memory_external_base = { workspace = true }
ash.workspace = true
smithay.workspace = true
compositor_kernel_vulkan_device_factory_base.workspace = true
compositor_kernel_vulkan_format_query_base.workspace = true
compositor_kernel_vulkan_renderer_error_base.workspace = true

[lib]
path = "lib.rs"
