[package]
name = "compositor_y5_surface_interface_base"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_y5_surface_interface_core = { workspace = true }
compositor_y5_select_system_base = { workspace = true }
compositor_y5_window_interface_record = { workspace = true }
uuid = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_y5_surface_system_base = { workspace = true }
compositor_y5_canvas_system_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_orchestration_core_state_base.workspace = true
compositor_monitor_runtime_surface_base.workspace = true
compositor_support_iced_core_engine_base.workspace = true
compositor_monitor_compositor_iced_base.workspace = true
compositor_support_smithay_state_layershell_dispatch.workspace = true
compositor_y5_camera_transform_translate.workspace = true
compositor_model_environment_config_base.workspace = true
compositor_orchestration_draw_layer_base.workspace = true
compositor_support_system_storage_slot_base.workspace = true
compositor_support_smithay_state_space_base.workspace = true
compositor_support_world_host_space_base.workspace = true
compositor_support_world_order_track_base.workspace = true
compositor_y5_select_state_base.workspace = true
compositor_y5_surface_state_base.workspace = true


[lib]
path = "lib.rs"