[package]
name = "compositor_support_bevy_core_import_base"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_support_bevy_core_context_base = { workspace = true }
compositor_support_bevy_core_fault_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
smithay = { workspace = true }
wgpu = { workspace = true }
