[package]
name = "compositor_y5_picker_three_spawn"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
compositor_y5_picker_three_constant = { workspace = true }
compositor_y5_picker_three_layout = { workspace = true }
compositor_y5_picker_three_mesh = { workspace = true }
compositor_y5_picker_three_state = { workspace = true }
bevy = { workspace = true }

[lib]
path = "lib.rs"
