[package]
name = "compositor_pipeline_execute_offscreen_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_kernel_vulkan_memory_external_base = { workspace = true }
ash.workspace = true
compositor_kernel_vulkan_device_factory_base.workspace = true
compositor_kernel_vulkan_renderer_error_base.workspace = true
compositor_pipeline_execute_effect_base.workspace = true
compositor_kernel_vulkan_pipeline_composite_base.workspace = true

[build-dependencies]
naga.workspace = true

[lib]
path = "lib.rs"
