[package]
name = "compositor_kernel_vulkan_texture_image_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_kernel_vulkan_memory_external_base = { workspace = true }
compositor_kernel_vulkan_texture_image_inner = { workspace = true }
smithay.workspace = true
ash.workspace = true

[lib]
path = "lib.rs"
