[package]
name = "compositor_y5_guide_shader_create"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_draw_layer_base = { workspace = true }
compositor_y5_guide_interface_surface = { workspace = true }
compositor_y5_guide_shader_state = { workspace = true }
compositor_y5_guide_shader_view = { workspace = true }
compositor_y5_guide_state_base = { workspace = true }
compositor_y5_surface_draw_handle = { workspace = true }
compositor_y5_surface_protocol_base = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
