[package]
name = "compositor_support_smithay_dispatch_wire_color"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_environment_config_base = { workspace = true }
compositor_kernel_graphic_color_surface_base = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
