[package]
name = "compositor_background_two_worker_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_environment_background_base = { workspace = true }
smithay = { workspace = true }
compositor_background_two_worker_pane = { workspace = true }
compositor_background_two_worker_serve = { workspace = true }
compositor_background_two_worker_signal = { workspace = true }
compositor_background_two_worker_target = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }

[lib]
path = "lib.rs"
