[package]
name = "compositor_support_smithay_state_compositor_place"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
smithay = { workspace = true }
compositor_support_smithay_dispatch_state_base = { workspace = true }
compositor_support_smithay_dispatch_wire_trait = { workspace = true }

[lib]
path = "lib.rs"
