// Developer logging: bring error!/warn!/info!/trace!/abort! into scope.
#[macro_use]
extern crate compositor_model_debug_instance_record;

/// Raw libav (ffmpeg 8.x) bindings, generated by `build.rs` via bindgen.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes
)]
pub mod ffi;

mod capture;
mod common;
pub mod cuda;
mod dynload;
pub mod egl;
pub mod nvenc;
pub mod nvenc_cuda;
pub mod thread;
pub mod vaapi;

pub use capture::*;
pub use nvenc::NvencEncoder;
pub use nvenc_cuda::{Codec, NvencCudaEncoder};
pub use thread::EncoderThread;
pub use vaapi::VaapiEncoder;
