[package]
name = "compositor_background_two_worker_format"
version = "0.0.1"
edition = "2024"

[dependencies]
smithay = { workspace = true }
compositor_kernel_vulkan_format_query_base = { workspace = true }
compositor_kernel_vulkan_format_modifier_base = { workspace = true }
compositor_kernel_graphic_bridge_negotiate_compositor = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }

[lib]
path = "lib.rs"
