[package]
name = "compositor_y5_guide_shader_handle"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_configurator_settings_interface_handle = { workspace = true }
compositor_configurator_settings_surface_message = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_guide_shader_view = { workspace = true }
compositor_y5_guide_state_base = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
