[package]
name = "compositor_y5_audio_controller_interface"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
libpulse-binding.workspace = true
mpris.workspace = true
[lib]
path = "lib.rs"
