[package]
name = "compositor_y5_picker_surface_create"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_draw_layer_base = { workspace = true }
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_y5_surface_draw_handle = { workspace = true }
compositor_y5_surface_protocol_base = { workspace = true }
compositor_y5_picker_surface_view = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
