[package]
name = "compositor_y5_picker_seat_keyboard"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_y5_picker_pick_navigate = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_support_library_input_keyboard_base = { workspace = true }
compositor_support_smithay_dispatch_state_base = { workspace = true }
compositor_y5_picker_system_base = { workspace = true }
compositor_y5_picker_three_constant = { workspace = true }
compositor_y5_picker_command_base = { workspace = true }
compositor_y5_picker_world_base = { workspace = true }
compositor_y5_picker_interface_base = { workspace = true }
compositor_y5_picker_seat_iced = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
