[package]
name = "compositor_y5_window_decoration_element"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_pipeline_bundle_manifest_base = { workspace = true }
compositor_background_two_storage_base = { workspace = true }
compositor_y5_select_system_base = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_y5_canvas_system_base = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_y5_window_interface_draw.workspace = true
compositor_y5_window_draw_element.workspace = true
compositor_orchestration_core_state_base.workspace = true
compositor_y5_canvas_draw_context.workspace = true
compositor_y5_camera_transform_translate.workspace = true
compositor_y5_window_interface_record.workspace = true
[lib]
path = "lib.rs"
