[package]
name = "compositor_y5_guide_help_view"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_support_iced_core_engine_base = { workspace = true }
compositor_monitor_selection_font_base = { workspace = true }
compositor_y5_guide_menu_view = { workspace = true }
iced_core = { workspace = true }
iced_widget = { workspace = true }

[lib]
path = "lib.rs"
