[package]
name = "compositor_y5_picker_world_delete"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_support_system_persist_mark_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_support_world_host_space_base = { workspace = true }
compositor_y5_picker_system_base = { workspace = true }
compositor_y5_picker_state_base = { workspace = true }
smithay = { workspace = true }

uuid = { workspace = true }

[lib]
path = "lib.rs"
