[package]
name = "compositor_orchestration_environment_type_base"
version = "0.0.1"
edition = "2024"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_developer_environment_config_base = { workspace = true }
compositor_developer_environment_config_router = { workspace = true }

[lib]
path = "lib.rs"
