[package]
name = "compositor_kernel_vulkan_sync_fence_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_kernel_vulkan_sync_fence_syncfile = { workspace = true }
libc = { workspace = true }
ash.workspace = true
smithay.workspace = true
compositor_model_debug_instance_record.workspace = true

[lib]
path = "lib.rs"
