[package]
name = "compositor_y5_window_interface_dump"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_model_debug_instance_record = { workspace = true }
compositor_introspection_extraction_window_meta_types = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_window_interface_record = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
