[package]
name = "compositor_background_three_lock_build"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
bevy = { workspace = true }
compositor_support_bevy_core_bridge_base = { workspace = true }
compositor_support_bevy_core_placeholder_base = { workspace = true }
compositor_background_three_lock_anim = { workspace = true }
compositor_background_three_lock_apply = { workspace = true }
compositor_background_three_lock_material = { workspace = true }
compositor_background_three_lock_orbit = { workspace = true }
compositor_background_three_lock_shader = { workspace = true }
compositor_background_three_lock_spawn = { workspace = true }
compositor_background_three_lock_state = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
wgpu = { workspace = true }
