[package]
name = "compositor_background_two_worker_device"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_background_two_worker_ring = { workspace = true }
ash = { workspace = true }
smithay = { workspace = true }
compositor_kernel_vulkan_command_pool_base = { workspace = true }
compositor_kernel_vulkan_device_factory_base = { workspace = true }
compositor_kernel_vulkan_device_queue_base = { workspace = true }
compositor_kernel_vulkan_instance_factory_base = { workspace = true }
compositor_background_two_worker_physical = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }

[lib]
path = "lib.rs"
