[package]
name = "compositor_orchestration_environment_interface_lifecycle"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
