[package]
name = "compositor_y5_guide_interface_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_guide_state_base = { workspace = true }
compositor_y5_surface_interface_base = { workspace = true }
compositor_y5_window_interface_draw = { workspace = true }

[lib]
path = "lib.rs"
