[package]
name = "compositor_support_bevy_core_frame_base"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_model_environment_interface_base = { workspace = true }
compositor_support_bevy_core_context_base = { workspace = true }
compositor_support_bevy_core_element_base = { workspace = true }
compositor_support_bevy_core_error_base = { workspace = true }
compositor_support_bevy_core_handle_base = { workspace = true }
compositor_support_bevy_core_item_base = { workspace = true }
compositor_support_bevy_core_space_base = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
smithay = { workspace = true }
