[package]
name = "compositor_pipeline_execute_graph_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_pipeline_abi_seam_base = { workspace = true }
compositor_pipeline_abi_worldset_base = { workspace = true }
ash.workspace = true
compositor_kernel_vulkan_device_factory_base.workspace = true
compositor_kernel_vulkan_renderer_error_base.workspace = true
compositor_pipeline_execute_effect_base.workspace = true
compositor_orchestration_draw_dispatch_frame.workspace = true

compositor_orchestration_seat_pointer_publish.workspace = true
compositor_pipeline_abi_clock_base.workspace = true
[lib]
path = "lib.rs"
