[package]
name = "compositor_background_two_draw_parallax"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
compositor_pipeline_world_system_base = { workspace = true }
compositor_kernel_vulkan_memory_external_base = { workspace = true }
compositor_pipeline_abi_worldset_base = { workspace = true }
uuid = { workspace = true }
compositor_pipeline_build_seam_base = { workspace = true }
compositor_background_two_draw_offload = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_pipeline_build_place_base = { workspace = true }
compositor_background_two_worker_key = { workspace = true }
compositor_model_environment_background_base = { workspace = true }
compositor_background_two_draw_motion = { workspace = true }
compositor_background_two_worker_base = { workspace = true }
compositor_background_two_worker_signal = { workspace = true }
compositor_background_two_worker_shared = { workspace = true }
compositor_model_stats_registry_base = { workspace = true }
compositor_background_two_draw_select = { workspace = true }
compositor_background_two_draw_vulkan = { workspace = true }
compositor_pipeline_compile_spirv_base = { workspace = true }
compositor_pipeline_build_pipeline_base = { workspace = true }
compositor_pipeline_bundle_property_base = { workspace = true }
compositor_orchestration_draw_dispatch_frame = { workspace = true }
smithay = { workspace = true }
compositor_pipeline_abi_clock_base = { workspace = true }
