[package]
name = "compositor_y5_picker_command_base"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_support_system_persist_mark_base = { workspace = true }
compositor_y5_picker_name_pool = { workspace = true }
compositor_y5_picker_three_orient = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_picker_system_base = { workspace = true }
compositor_y5_picker_state_base = { workspace = true }
compositor_y5_picker_three_scene = { workspace = true }
compositor_y5_picker_surface_view = { workspace = true }
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_background_three_system_base = { workspace = true }

[lib]
path = "lib.rs"
