use compositor_installer_process_config_parse_base::Preset;

/// The canonical one-line install URL — the path `bootstrap.sh` is published at. The
/// docs and this script must name the SAME url, so it is defined once, here.
pub const INSTALL_URL: &str = "https://nourish.snowies.com/install";

/// The `/usr/bin/y5.compositor.update` script.
///
/// The installed compositor binary IS the marker: there is no separate state file to
/// fall out of sync with the disk. If the binary is gone the install is gone (or was
/// never made) and there is nothing to update, so this refuses rather than quietly
/// turning itself into an installer.
///
/// The bootstrap is downloaded to a file and run with **stdin closed**, not piped from
/// curl. Both halves matter: piping would leave the installer's prompts reading the
/// tail of the script itself, and closing stdin is what makes every prompt take its
/// default — `parse.prompt` treats EOF as "keep the default", so no separate
/// non-interactive flag is needed. `Y5_*` variables (including
/// `Y5_INSTALL_ARGS=--dry-run`) pass straight through to the bootstrap.
pub fn update_script(p: &Preset) -> String {
    format!(
        "#!/bin/bash\n\
         # /usr/bin/y5.compositor.update — generated by the y5 installer.\n\
         # Re-runs the published bootstrap; every installer prompt takes its default.\n\
         set -euo pipefail\n\
         \n\
         BIN=/usr/bin/{binary}\n\
         if [ ! -x \"$BIN\" ]; then\n\
         \x20   echo \"y5 is not installed (no $BIN) — nothing to update.\" >&2\n\
         \x20   echo \"To install: curl -fsSL {url} | bash\" >&2\n\
         \x20   exit 1\n\
         fi\n\
         \n\
         URL=\"${{Y5_INSTALL_URL:-{url}}}\"\n\
         tmp=\"$(mktemp)\"\n\
         trap 'rm -f \"$tmp\"' EXIT\n\
         echo \":: fetching $URL\"\n\
         curl -fsSL \"$URL\" -o \"$tmp\"\n\
         echo \":: running the installer with default answers\"\n\
         bash \"$tmp\" < /dev/null\n",
        binary = p.binary,
        url = INSTALL_URL,
    )
}
