[package]
name = "compositor_background_two_worker_pane"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_background_two_worker_key = { workspace = true }
compositor_pipeline_execute_warpmap_base = { workspace = true }
compositor_pipeline_execute_graph_base = { workspace = true }
ash = { workspace = true }
smithay = { workspace = true }
compositor_background_two_worker_buffers = { workspace = true }
compositor_background_two_worker_target = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_background_two_worker_history.workspace = true

[lib]
path = "lib.rs"
