[package]
name = "compositor_y5_guide_interface_handle"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_guide_interface_base = { workspace = true }
compositor_y5_guide_menu_view = { workspace = true }
compositor_y5_overview_interface_base = { workspace = true }
compositor_y5_overview_state_base = { workspace = true }

[lib]
path = "lib.rs"
