[package]
name = "compositor_background_two_state_base"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_pipeline_build_pipeline_base = { workspace = true }
compositor_pipeline_bundle_manifest_base = { workspace = true }
compositor_pipeline_host_map_base = { workspace = true }
compositor_pipeline_bundle_property_base = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_background_two_draw_element.workspace = true
[lib]
path = "lib.rs"