use compositor_installer_process_config_parse_base::Preset;

/// The /usr/bin wrapper script: exports session identity + a few third-party debug
/// vars, then execs the compositor binary.
///
/// It deliberately does NOT write settings.json. The compositor's config is owned by
/// the user (authored with the `y5.compositor.settings` tool); a wrapper that rewrote
/// it every launch would clobber those edits. If the file is absent the wrapper points
/// the user at the tool and refuses to launch — the compositor panics without it, so a
/// clear message beats a stack trace.
pub fn wrapper_desktop(p: &Preset) -> String {
    format!(
        "#!/bin/bash\n\
         # /usr/bin/{wrapper} — ExecStart of {service}\n\
         # Generated by the y5 installer. Re-run the installer to regenerate.\n\
         \n\
         export RUST_LOG=info,smithay=info\n\
         export MESA_DEBUG=1\n\
         \n\
         # Session identity — must match DesktopNames= in the wayland-session entry.\n\
         export XDG_CURRENT_DESKTOP={desktop}\n\
         export XDG_SESSION_TYPE=wayland\n\
         \n\
         # The compositor reads ALL of its configuration from settings.json (every field\n\
         # required; it panics if the file is missing or partial). This wrapper NEVER\n\
         # writes that file — it belongs to the user. Configure it with the\n\
         # 'y5.compositor.settings' tool. If it's absent, say so and stop rather than\n\
         # launching into a panic.\n\
         _y5_cfg=\"${{XDG_CONFIG_HOME:-$HOME/.config}}/y5.compositor\"\n\
         if [ ! -f \"$_y5_cfg/settings.json\" ]; then\n\
         \techo \"y5: no configuration at $_y5_cfg/settings.json\" >&2\n\
         \techo \"y5: run 'y5.compositor.settings' to configure, then start this session again.\" >&2\n\
         \texit 1\n\
         fi\n\
         \n\
         exec /usr/bin/{binary}\n",
        wrapper = p.wrapper,
        service = p.service,
        desktop = p.desktop_name,
        binary = p.binary,
    )
}

/// systemd user service (modeled on the reference y5.*.service units).
pub fn systemd_service(p: &Preset) -> String {
    format!(
        "# ~/.config/systemd/user/{service}\n\
         [Unit]\n\
         Description=Y5 Wayland compositor ({label})\n\
         BindsTo=graphical-session.target\n\
         Before=graphical-session.target\n\
         Wants=graphical-session-pre.target\n\
         After=graphical-session-pre.target\n\
         Wants=xdg-desktop-autostart.target\n\
         Before=xdg-desktop-autostart.target\n\
         \n\
         [Service]\n\
         Slice=session.slice\n\
         Type=exec\n\
         ExecStart=/usr/bin/{wrapper}\n",
        service = p.service,
        label = p.label,
        wrapper = p.wrapper,
    )
}

/// The shutdown target paired with each session (from the reference).
pub fn shutdown_target() -> String {
    "[Unit]\n\
     Description=Shutdown running Y5 session\n\
     DefaultDependencies=no\n\
     StopWhenUnneeded=yes\n\
     Conflicts=graphical-session.target graphical-session-pre.target\n\
     After=graphical-session.target graphical-session-pre.target\n"
        .to_string()
}

/// /usr/share/wayland-sessions entry the display manager lists.
pub fn wayland_session(p: &Preset) -> String {
    format!(
        "[Desktop Entry]\n\
         Name={name}\n\
         Comment=Y5 Compositor — {label}\n\
         Exec=systemctl --user --wait start {service}\n\
         Type=Application\n\
         DesktopNames={desktop}\n",
        name = p.session_name,
        label = p.label,
        service = p.service,
        desktop = p.desktop_name,
    )
}
