[package]
name = "compositor_y5_picker_surface_view"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_model_debug_instance_record = { workspace = true }
compositor_support_iced_core_engine_base = { workspace = true }
iced_core = { workspace = true }
iced_widget = { workspace = true }

[lib]
path = "lib.rs"
