[package]
name = "compositor_y5_canvas_state_base"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_y5_select_state_base = { workspace = true }
compositor_y5_group_state_base.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_y5_canvas_input_state.workspace = true
compositor_support_system_input_event_base.workspace = true
[lib]
path = "lib.rs"
