[package]
name = "compositor_support_library_debug_client_base"
version = "0.1.0"
edition = "2024"

[dependencies]
compositor_support_library_process_child_hygiene = { workspace = true }
tracing = {workspace = true}
tracing-subscriber = { workspace = true}
bitflags = {workspace = true}
smithay = {workspace = true}
#use_system_lib: Tells Smithay to look for the actual .so files on your Fedora system (the NVIDIA drivers).
#backend_egl: Specifically turns on the NVIDIA-friendly EGL code path.
#1. What is GlesRenderer?
#Strictly GPU? Yes. It uses your RTX 4090 to compile shaders and draw pixels directly in VRAM.
#Is it EGL? Not exactly, but they are partners.
#
#EGL is the "Glue": It talks to the operating system, manages the GPU context, and creates surfaces.
#
#GLES is the "Paintbrush": It is the actual API used to tell the GPU what to draw on those surfaces.
#
#GlesRenderer is the Object in Smithay that holds both the paintbrush and the glue.

[lib]
path = "lib.rs"
