[package]
name = "compositor_y5_osk_board_create"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_monitor_compositor_iced_base = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_orchestration_draw_layer_base = { workspace = true }
compositor_monitor_selection_font_base = { workspace = true }
compositor_y5_surface_draw_handle = { workspace = true }
compositor_y5_surface_protocol_base = { workspace = true }
compositor_y5_osk_board_view = { workspace = true }
compositor_y5_osk_board_state = { workspace = true }
compositor_y5_navigator_state_base = { workspace = true }
compositor_y5_navigator_travel_state = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_support_world_order_track_base = { workspace = true }
smithay = { workspace = true }
uuid = { workspace = true }

[lib]
path = "lib.rs"
