[package]
name = "compositor_background_two_worker_target"
version = "0.0.1"
edition = "2024"

[dependencies]
ash = { workspace = true }
smithay = { workspace = true }
compositor_model_environment_tearing_rate = { workspace = true }
compositor_kernel_vulkan_device_factory_base = { workspace = true }

[lib]
path = "lib.rs"
