[package]
name = "compositor_y5_picker_seat_cursor"
version = "0.0.1"
edition = "2024"

[dependencies]
compositor_orchestration_seat_pointer_publish = { workspace = true }
compositor_model_debug_instance_record = { workspace = true }
compositor_orchestration_core_state_base = { workspace = true }
compositor_y5_picker_seat_iced = { workspace = true }
smithay = { workspace = true }

[lib]
path = "lib.rs"
