[package]
name = "compositor_y5_window_interface_draw"
version = "0.0.1"
edition = "2024"


[dependencies]
compositor_y5_group_system_base = { workspace = true }
compositor_y5_camera_state_base = { workspace = true }
compositor_y5_lock_system_base = { workspace = true }
compositor_y5_camera_system_base = { workspace = true }
compositor_y5_canvas_system_base = { workspace = true }
compositor_y5_group_state_base.workspace = true
compositor_y5_group_interface_base.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bitflags = { workspace = true }
smithay = { workspace = true }
compositor_orchestration_core_state_base.workspace = true
compositor_y5_camera_transform_translate.workspace = true
compositor_model_environment_config_base.workspace = true
compositor_y5_canvas_draw_context.workspace = true
compositor_y5_window_interface_record.workspace=true
uuid.workspace = true
[lib]
path = "lib.rs"
